import {
  Atom,
  Baby,
  Bird,
  BookOpen,
  Brain,
  Bug,
  Building2,
  CalendarDays,
  Castle,
  Cat,
  Church,
  Circle,
  Clock,
  Cloud,
  Coins,
  Compass,
  Crown,
  Dna,
  Dog,
  Droplet,
  Eye,
  Feather,
  Fish,
  Flag,
  FlaskConical,
  Flame,
  Footprints,
  Gem,
  Ghost,
  GitFork,
  Globe,
  Hammer,
  Handshake,
  Heart,
  HeartCrack,
  Hexagon,
  Hourglass,
  House,
  Key,
  Landmark,
  Leaf,
  Lightbulb,
  Link,
  Map,
  MapPin,
  Moon,
  Mountain,
  Music,
  Network,
  Package,
  PawPrint,
  Scroll,
  Shield,
  Ship,
  Skull,
  Snowflake,
  Sparkles,
  Square,
  Star,
  Sun,
  Sword,
  Swords,
  Tag,
  TentTree,
  Trees,
  Triangle,
  User,
  UserRound,
  Users,
  WandSparkles,
  Waves,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * Catálogo de iconos elegibles para los tipos. El dominio solo guarda el nombre;
 * un nombre desconocido se muestra con el icono genérico.
 */
export const TYPE_ICONS: Record<string, { icon: LucideIcon; label: string }> = {
  circle: { icon: Circle, label: 'Genérico' },
  user: { icon: User, label: 'Persona' },
  'user-round': { icon: UserRound, label: 'Personaje' },
  users: { icon: Users, label: 'Grupo' },
  baby: { icon: Baby, label: 'Descendencia' },
  crown: { icon: Crown, label: 'Realeza' },
  castle: { icon: Castle, label: 'Castillo' },
  landmark: { icon: Landmark, label: 'Institución' },
  church: { icon: Church, label: 'Templo' },
  building: { icon: Building2, label: 'Edificio' },
  house: { icon: House, label: 'Hogar' },
  'tent-tree': { icon: TentTree, label: 'Campamento' },
  'map-pin': { icon: MapPin, label: 'Lugar' },
  map: { icon: Map, label: 'Mapa' },
  globe: { icon: Globe, label: 'Mundo' },
  compass: { icon: Compass, label: 'Región' },
  mountain: { icon: Mountain, label: 'Montaña' },
  trees: { icon: Trees, label: 'Bosque' },
  waves: { icon: Waves, label: 'Mar' },
  ship: { icon: Ship, label: 'Barco' },
  flag: { icon: Flag, label: 'Facción' },
  shield: { icon: Shield, label: 'Orden' },
  sword: { icon: Sword, label: 'Arma' },
  swords: { icon: Swords, label: 'Conflicto' },
  sparkles: { icon: Sparkles, label: 'Divinidad' },
  'wand-sparkles': { icon: WandSparkles, label: 'Magia' },
  flame: { icon: Flame, label: 'Fuego' },
  droplet: { icon: Droplet, label: 'Agua' },
  wind: { icon: Wind, label: 'Aire' },
  leaf: { icon: Leaf, label: 'Naturaleza' },
  snowflake: { icon: Snowflake, label: 'Hielo' },
  zap: { icon: Zap, label: 'Energía' },
  sun: { icon: Sun, label: 'Sol' },
  moon: { icon: Moon, label: 'Luna' },
  star: { icon: Star, label: 'Estrella' },
  cloud: { icon: Cloud, label: 'Cielo' },
  gem: { icon: Gem, label: 'Gema' },
  coins: { icon: Coins, label: 'Riqueza' },
  key: { icon: Key, label: 'Llave' },
  package: { icon: Package, label: 'Objeto' },
  hammer: { icon: Hammer, label: 'Oficio' },
  wrench: { icon: Wrench, label: 'Herramienta' },
  'flask-conical': { icon: FlaskConical, label: 'Alquimia' },
  atom: { icon: Atom, label: 'Ciencia' },
  dna: { icon: Dna, label: 'Linaje' },
  brain: { icon: Brain, label: 'Mente' },
  eye: { icon: Eye, label: 'Visión' },
  lightbulb: { icon: Lightbulb, label: 'Idea' },
  'book-open': { icon: BookOpen, label: 'Libro' },
  scroll: { icon: Scroll, label: 'Pergamino' },
  feather: { icon: Feather, label: 'Escritura' },
  music: { icon: Music, label: 'Música' },
  'calendar-days': { icon: CalendarDays, label: 'Evento' },
  clock: { icon: Clock, label: 'Tiempo' },
  hourglass: { icon: Hourglass, label: 'Era' },
  skull: { icon: Skull, label: 'Muerte' },
  ghost: { icon: Ghost, label: 'Espíritu' },
  heart: { icon: Heart, label: 'Amor' },
  'heart-crack': { icon: HeartCrack, label: 'Ruptura' },
  handshake: { icon: Handshake, label: 'Alianza' },
  link: { icon: Link, label: 'Vínculo' },
  'git-fork': { icon: GitFork, label: 'Rama' },
  network: { icon: Network, label: 'Red' },
  footprints: { icon: Footprints, label: 'Viaje' },
  'paw-print': { icon: PawPrint, label: 'Criatura' },
  cat: { icon: Cat, label: 'Felino' },
  dog: { icon: Dog, label: 'Cánido' },
  bird: { icon: Bird, label: 'Ave' },
  fish: { icon: Fish, label: 'Pez' },
  bug: { icon: Bug, label: 'Insecto' },
  tag: { icon: Tag, label: 'Etiqueta' },
  hexagon: { icon: Hexagon, label: 'Hexágono' },
  square: { icon: Square, label: 'Cuadrado' },
  triangle: { icon: Triangle, label: 'Triángulo' },
};

export function typeIcon(name: string | undefined): LucideIcon {
  return (name && TYPE_ICONS[name]?.icon) || Circle;
}
