import {
  Atom,
  Baby,
  Bird,
  BookOpen,
  Brain,
  Bug,
  Building2,
  CalendarDays,
  Castle,
  Cat,
  Church,
  Circle,
  Clock,
  Cloud,
  Coins,
  Compass,
  Crown,
  Dna,
  Dog,
  Droplet,
  Eye,
  Feather,
  Fish,
  Flag,
  FlaskConical,
  Flame,
  Footprints,
  Gem,
  Ghost,
  GitFork,
  Globe,
  Hammer,
  Handshake,
  Heart,
  HeartCrack,
  Hexagon,
  Hourglass,
  House,
  Key,
  Landmark,
  Leaf,
  Lightbulb,
  Link,
  Map,
  MapPin,
  Moon,
  Mountain,
  Music,
  Network,
  Package,
  PawPrint,
  Scroll,
  Shield,
  Ship,
  Skull,
  Snowflake,
  Sparkles,
  Square,
  Star,
  Sun,
  Sword,
  Swords,
  Tag,
  TentTree,
  Trees,
  Triangle,
  User,
  UserRound,
  Users,
  WandSparkles,
  Waves,
  Wind,
  Wrench,
  Zap,
  Amphora,
  Anchor,
  Apple,
  Award,
  Axe,
  Badge,
  Bean,
  Bed,
  Beer,
  Bell,
  BellRing,
  Biohazard,
  Bomb,
  Bone,
  Book,
  BowArrow,
  Boxes,
  BrickWall,
  CableCar,
  Car,
  Carrot,
  CircleDot,
  CloudLightning,
  CloudRain,
  CloudSnow,
  Clover,
  Coffee,
  Cross,
  Crosshair,
  Diamond,
  Dice5,
  Drama,
  Droplets,
  Drum,
  Earth,
  Egg,
  Factory,
  Fence,
  FlagTriangleLeft,
  FlameKindling,
  Flashlight,
  Flower,
  Flower2,
  Fuel,
  Gavel,
  Gift,
  Glasses,
  GraduationCap,
  Grape,
  Guitar,
  Ham,
  Hand,
  HandCoins,
  HardHat,
  HatGlasses,
  Haze,
  HeartHandshake,
  HeartOff,
  HeartPulse,
  Hotel,
  Infinity as InfinityIcon,
  KeyRound,
  Keyboard,
  Lamp,
  LampDesk,
  Library,
  Lock,
  Luggage,
  Mail,
  MapPinned,
  Medal,
  Megaphone,
  Mic,
  Microscope,
  Milestone,
  Milk,
  MoonStar,
  MountainSnow,
  Octagon,
  Orbit,
  Origami,
  Paintbrush,
  Palette,
  Panda,
  PenTool,
  Pencil,
  Pentagon,
  PersonStanding,
  Pickaxe,
  Pill,
  Plane,
  Plug,
  PocketKnife,
  Puzzle,
  Pyramid,
  Rabbit,
  Radiation,
  Radio,
  Rainbow,
  Rat,
  Recycle,
  Rocket,
  Ruler,
  Sailboat,
  Scale,
  School,
  Scissors,
  ScrollText,
  Shell,
  ShieldAlert,
  ShieldCheck,
  ShieldHalf,
  ShipWheel,
  Shirt,
  Shovel,
  Shrub,
  Siren,
  Snail,
  Spade,
  Sparkle,
  Speech,
  Sprout,
  Squirrel,
  Stars,
  Stethoscope,
  Store,
  SunMoon,
  Sunrise,
  Sunset,
  Syringe,
  Target,
  Telescope,
  Tent,
  TestTube,
  Theater,
  Thermometer,
  Ticket,
  Tornado,
  Tractor,
  TrainFront,
  TreeDeciduous,
  TreePine,
  Trophy,
  Turtle,
  Umbrella,
  UserCog,
  UserRoundCheck,
  UserRoundPen,
  UserRoundSearch,
  Utensils,
  Vault,
  VenetianMask,
  Wallet,
  Wand,
  Warehouse,
  Watch,
  Wheat,
  Wine,
  Worm,
  type LucideIcon,
} from 'lucide-react';

/**
 * Catálogo de iconos elegibles para los tipos. El dominio solo guarda el nombre;
 * un nombre desconocido se muestra con el icono genérico.
 */
export const TYPE_ICONS: Record<string, { icon: LucideIcon; label: string }> = {
  circle: { icon: Circle, label: 'Genérico' },
  user: { icon: User, label: 'Persona' },
  'user-round': { icon: UserRound, label: 'Personaje' },
  users: { icon: Users, label: 'Grupo' },
  baby: { icon: Baby, label: 'Descendencia' },
  crown: { icon: Crown, label: 'Realeza' },
  castle: { icon: Castle, label: 'Castillo' },
  landmark: { icon: Landmark, label: 'Institución' },
  church: { icon: Church, label: 'Templo' },
  building: { icon: Building2, label: 'Edificio' },
  house: { icon: House, label: 'Hogar' },
  'tent-tree': { icon: TentTree, label: 'Campamento' },
  'map-pin': { icon: MapPin, label: 'Lugar' },
  map: { icon: Map, label: 'Mapa' },
  globe: { icon: Globe, label: 'Mundo' },
  compass: { icon: Compass, label: 'Región' },
  mountain: { icon: Mountain, label: 'Montaña' },
  trees: { icon: Trees, label: 'Bosque' },
  waves: { icon: Waves, label: 'Mar' },
  ship: { icon: Ship, label: 'Barco' },
  flag: { icon: Flag, label: 'Facción' },
  shield: { icon: Shield, label: 'Orden' },
  sword: { icon: Sword, label: 'Arma' },
  swords: { icon: Swords, label: 'Conflicto' },
  sparkles: { icon: Sparkles, label: 'Divinidad' },
  'wand-sparkles': { icon: WandSparkles, label: 'Magia' },
  flame: { icon: Flame, label: 'Fuego' },
  droplet: { icon: Droplet, label: 'Agua' },
  wind: { icon: Wind, label: 'Aire' },
  leaf: { icon: Leaf, label: 'Naturaleza' },
  snowflake: { icon: Snowflake, label: 'Hielo' },
  zap: { icon: Zap, label: 'Energía' },
  sun: { icon: Sun, label: 'Sol' },
  moon: { icon: Moon, label: 'Luna' },
  star: { icon: Star, label: 'Estrella' },
  cloud: { icon: Cloud, label: 'Cielo' },
  gem: { icon: Gem, label: 'Gema' },
  coins: { icon: Coins, label: 'Riqueza' },
  key: { icon: Key, label: 'Llave' },
  package: { icon: Package, label: 'Objeto' },
  hammer: { icon: Hammer, label: 'Oficio' },
  wrench: { icon: Wrench, label: 'Herramienta' },
  'flask-conical': { icon: FlaskConical, label: 'Alquimia' },
  atom: { icon: Atom, label: 'Ciencia' },
  dna: { icon: Dna, label: 'Linaje' },
  brain: { icon: Brain, label: 'Mente' },
  eye: { icon: Eye, label: 'Visión' },
  lightbulb: { icon: Lightbulb, label: 'Idea' },
  'book-open': { icon: BookOpen, label: 'Libro' },
  scroll: { icon: Scroll, label: 'Pergamino' },
  feather: { icon: Feather, label: 'Escritura' },
  music: { icon: Music, label: 'Música' },
  'calendar-days': { icon: CalendarDays, label: 'Evento' },
  clock: { icon: Clock, label: 'Tiempo' },
  hourglass: { icon: Hourglass, label: 'Era' },
  skull: { icon: Skull, label: 'Muerte' },
  ghost: { icon: Ghost, label: 'Espíritu' },
  heart: { icon: Heart, label: 'Amor' },
  'heart-crack': { icon: HeartCrack, label: 'Ruptura' },
  handshake: { icon: Handshake, label: 'Alianza' },
  link: { icon: Link, label: 'Vínculo' },
  'git-fork': { icon: GitFork, label: 'Rama' },
  network: { icon: Network, label: 'Red' },
  footprints: { icon: Footprints, label: 'Viaje' },
  'paw-print': { icon: PawPrint, label: 'Criatura' },
  cat: { icon: Cat, label: 'Felino' },
  dog: { icon: Dog, label: 'Cánido' },
  bird: { icon: Bird, label: 'Ave' },
  fish: { icon: Fish, label: 'Pez' },
  bug: { icon: Bug, label: 'Insecto' },
  tag: { icon: Tag, label: 'Etiqueta' },
  hexagon: { icon: Hexagon, label: 'Hexágono' },
  square: { icon: Square, label: 'Cuadrado' },
  triangle: { icon: Triangle, label: 'Triángulo' },
  // Ampliación (2026-10-04): personas, lugares, naturaleza, criaturas, objetos y conceptos.
  'person-standing': { icon: PersonStanding, label: 'Figura' },
  'user-round-pen': { icon: UserRoundPen, label: 'Autor' },
  'user-round-search': { icon: UserRoundSearch, label: 'Investigador' },
  'user-round-check': { icon: UserRoundCheck, label: 'Aliado' },
  'user-cog': { icon: UserCog, label: 'Artesano' },
  'hat-glasses': { icon: HatGlasses, label: 'Disfraz' },
  'venetian-mask': { icon: VenetianMask, label: 'Máscara' },
  drama: { icon: Drama, label: 'Drama' },
  theater: { icon: Theater, label: 'Teatro' },
  speech: { icon: Speech, label: 'Discurso' },
  megaphone: { icon: Megaphone, label: 'Heraldo' },
  'graduation-cap': { icon: GraduationCap, label: 'Erudito' },
  stethoscope: { icon: Stethoscope, label: 'Sanador' },
  'hard-hat': { icon: HardHat, label: 'Obrero' },
  badge: { icon: Badge, label: 'Insignia' },
  award: { icon: Award, label: 'Distinción' },
  trophy: { icon: Trophy, label: 'Trofeo' },
  medal: { icon: Medal, label: 'Medalla' },
  tent: { icon: Tent, label: 'Tienda de campaña' },
  hotel: { icon: Hotel, label: 'Posada' },
  store: { icon: Store, label: 'Comercio' },
  warehouse: { icon: Warehouse, label: 'Almacén' },
  factory: { icon: Factory, label: 'Fábrica' },
  school: { icon: School, label: 'Escuela' },
  library: { icon: Library, label: 'Biblioteca' },
  bed: { icon: Bed, label: 'Refugio' },
  fence: { icon: Fence, label: 'Frontera' },
  'brick-wall': { icon: BrickWall, label: 'Muralla' },
  pyramid: { icon: Pyramid, label: 'Pirámide' },
  amphora: { icon: Amphora, label: 'Ruina' },
  milestone: { icon: Milestone, label: 'Hito' },
  'map-pinned': { icon: MapPinned, label: 'Enclave' },
  'cable-car': { icon: CableCar, label: 'Paso de montaña' },
  'train-front': { icon: TrainFront, label: 'Tren' },
  car: { icon: Car, label: 'Vehículo' },
  plane: { icon: Plane, label: 'Vuelo' },
  rocket: { icon: Rocket, label: 'Cohete' },
  sailboat: { icon: Sailboat, label: 'Velero' },
  'ship-wheel': { icon: ShipWheel, label: 'Timón' },
  anchor: { icon: Anchor, label: 'Puerto' },
  'tree-pine': { icon: TreePine, label: 'Pino' },
  'tree-deciduous': { icon: TreeDeciduous, label: 'Árbol' },
  shrub: { icon: Shrub, label: 'Arbusto' },
  sprout: { icon: Sprout, label: 'Brote' },
  flower: { icon: Flower, label: 'Flor' },
  'flower-2': { icon: Flower2, label: 'Flor silvestre' },
  clover: { icon: Clover, label: 'Trébol' },
  wheat: { icon: Wheat, label: 'Cosecha' },
  'mountain-snow': { icon: MountainSnow, label: 'Cumbre' },
  earth: { icon: Earth, label: 'Tierra' },
  orbit: { icon: Orbit, label: 'Órbita' },
  stars: { icon: Stars, label: 'Estrellas' },
  'moon-star': { icon: MoonStar, label: 'Noche' },
  sunrise: { icon: Sunrise, label: 'Amanecer' },
  sunset: { icon: Sunset, label: 'Atardecer' },
  'sun-moon': { icon: SunMoon, label: 'Ciclo' },
  'cloud-rain': { icon: CloudRain, label: 'Lluvia' },
  'cloud-snow': { icon: CloudSnow, label: 'Nieve' },
  'cloud-lightning': { icon: CloudLightning, label: 'Tormenta' },
  tornado: { icon: Tornado, label: 'Tornado' },
  rainbow: { icon: Rainbow, label: 'Arcoíris' },
  haze: { icon: Haze, label: 'Niebla' },
  droplets: { icon: Droplets, label: 'Gotas' },
  rabbit: { icon: Rabbit, label: 'Conejo' },
  rat: { icon: Rat, label: 'Rata' },
  squirrel: { icon: Squirrel, label: 'Ardilla' },
  turtle: { icon: Turtle, label: 'Tortuga' },
  snail: { icon: Snail, label: 'Caracol' },
  worm: { icon: Worm, label: 'Gusano' },
  panda: { icon: Panda, label: 'Oso' },
  shell: { icon: Shell, label: 'Concha' },
  bone: { icon: Bone, label: 'Hueso' },
  egg: { icon: Egg, label: 'Huevo' },
  'bow-arrow': { icon: BowArrow, label: 'Arco' },
  axe: { icon: Axe, label: 'Hacha' },
  'pocket-knife': { icon: PocketKnife, label: 'Daga' },
  'shield-half': { icon: ShieldHalf, label: 'Escudo partido' },
  'shield-check': { icon: ShieldCheck, label: 'Protección' },
  'shield-alert': { icon: ShieldAlert, label: 'Amenaza' },
  bomb: { icon: Bomb, label: 'Explosivo' },
  crosshair: { icon: Crosshair, label: 'Objetivo' },
  target: { icon: Target, label: 'Diana' },
  'dice-5': { icon: Dice5, label: 'Azar' },
  puzzle: { icon: Puzzle, label: 'Enigma' },
  lock: { icon: Lock, label: 'Secreto' },
  'key-round': { icon: KeyRound, label: 'Llave antigua' },
  vault: { icon: Vault, label: 'Cámara acorazada' },
  wallet: { icon: Wallet, label: 'Bolsa' },
  'hand-coins': { icon: HandCoins, label: 'Tributo' },
  gift: { icon: Gift, label: 'Regalo' },
  diamond: { icon: Diamond, label: 'Diamante' },
  lamp: { icon: Lamp, label: 'Lámpara' },
  'lamp-desk': { icon: LampDesk, label: 'Escritorio' },
  flashlight: { icon: Flashlight, label: 'Linterna' },
  'flame-kindling': { icon: FlameKindling, label: 'Hoguera' },
  pickaxe: { icon: Pickaxe, label: 'Mina' },
  shovel: { icon: Shovel, label: 'Excavación' },
  scissors: { icon: Scissors, label: 'Corte' },
  ruler: { icon: Ruler, label: 'Medida' },
  'pen-tool': { icon: PenTool, label: 'Diseño' },
  paintbrush: { icon: Paintbrush, label: 'Pintura' },
  palette: { icon: Palette, label: 'Arte' },
  pencil: { icon: Pencil, label: 'Boceto' },
  origami: { icon: Origami, label: 'Papel' },
  book: { icon: Book, label: 'Tomo' },
  'scroll-text': { icon: ScrollText, label: 'Crónica' },
  mail: { icon: Mail, label: 'Carta' },
  bell: { icon: Bell, label: 'Campana' },
  'bell-ring': { icon: BellRing, label: 'Alarma' },
  siren: { icon: Siren, label: 'Alerta' },
  drum: { icon: Drum, label: 'Tambor' },
  guitar: { icon: Guitar, label: 'Laúd' },
  mic: { icon: Mic, label: 'Voz' },
  radio: { icon: Radio, label: 'Señal' },
  telescope: { icon: Telescope, label: 'Observatorio' },
  microscope: { icon: Microscope, label: 'Estudio' },
  'test-tube': { icon: TestTube, label: 'Experimento' },
  syringe: { icon: Syringe, label: 'Veneno' },
  pill: { icon: Pill, label: 'Remedio' },
  thermometer: { icon: Thermometer, label: 'Fiebre' },
  'heart-pulse': { icon: HeartPulse, label: 'Vida' },
  biohazard: { icon: Biohazard, label: 'Plaga' },
  radiation: { icon: Radiation, label: 'Radiación' },
  infinity: { icon: InfinityIcon, label: 'Eternidad' },
  recycle: { icon: Recycle, label: 'Ciclo vital' },
  scale: { icon: Scale, label: 'Justicia' },
  gavel: { icon: Gavel, label: 'Ley' },
  cross: { icon: Cross, label: 'Cruz' },
  'heart-handshake': { icon: HeartHandshake, label: 'Afecto' },
  'heart-off': { icon: HeartOff, label: 'Desamor' },
  hand: { icon: Hand, label: 'Mano' },
  fuel: { icon: Fuel, label: 'Combustible' },
  plug: { icon: Plug, label: 'Conexión' },
  keyboard: { icon: Keyboard, label: 'Máquina' },
  watch: { icon: Watch, label: 'Reloj' },
  ticket: { icon: Ticket, label: 'Entrada' },
  luggage: { icon: Luggage, label: 'Equipaje' },
  umbrella: { icon: Umbrella, label: 'Paraguas' },
  shirt: { icon: Shirt, label: 'Ropa' },
  glasses: { icon: Glasses, label: 'Gafas' },
  coffee: { icon: Coffee, label: 'Café' },
  wine: { icon: Wine, label: 'Vino' },
  beer: { icon: Beer, label: 'Cerveza' },
  milk: { icon: Milk, label: 'Leche' },
  utensils: { icon: Utensils, label: 'Comida' },
  apple: { icon: Apple, label: 'Fruta' },
  grape: { icon: Grape, label: 'Viña' },
  carrot: { icon: Carrot, label: 'Huerta' },
  ham: { icon: Ham, label: 'Carne' },
  bean: { icon: Bean, label: 'Semilla' },
  boxes: { icon: Boxes, label: 'Mercancía' },
  tractor: { icon: Tractor, label: 'Granja' },
  wand: { icon: Wand, label: 'Varita' },
  sparkle: { icon: Sparkle, label: 'Chispa' },
  'flag-triangle-left': { icon: FlagTriangleLeft, label: 'Estandarte' },
  spade: { icon: Spade, label: 'Pica' },
  pentagon: { icon: Pentagon, label: 'Pentágono' },
  octagon: { icon: Octagon, label: 'Octágono' },
  'circle-dot': { icon: CircleDot, label: 'Punto' },
};

export function typeIcon(name: string | undefined): LucideIcon {
  return (name && TYPE_ICONS[name]?.icon) || Circle;
}
