import { useMemo } from 'react';
import { getSchema, nodeLabel } from '../../domain/selectors';
import type { Selection } from '../../domain/types';
import { useApp } from '../../state/AppContext';
export function GraphCanvas({selection,onSelect}:{selection:Selection;onSelect:(s:Selection)=>void}){const{project}=useApp();const positions=useMemo(()=>{const out=new Map<string,{x:number;y:number}>();const levels=new Map<number,string[]>();const depth=(id:string):number=>{const n=project.nodes.find(x=>x.id===id);return n?.parentId?1+depth(n.parentId):0};project.nodes.forEach(n=>{const d=depth(n.id);levels.set(d,[...(levels.get(d)||[]),n.id])});levels.forEach((ids,d)=>ids.forEach((id,i)=>out.set(id,{x:70+d*260,y:55+i*105})));return out},[project.nodes]);
 if(!project.nodes.length)return <section className="workspace"><div className="empty-state"><div><h2>Un lienzo para tus ideas</h2><p>Define un tipo de entidad y crea el primer nodo desde el panel izquierdo.</p></div></div></section>;
 return <section className="workspace"><div className="workspace-toolbar"><strong>Vista general</strong><div className="spacer"/><span>{project.nodes.length} nodos · {project.relations.length} relaciones</span></div><div className="canvas"><svg width={Math.max(900,...[...positions.values()].map(p=>p.x+240))} height={Math.max(650,...[...positions.values()].map(p=>p.y+100))}>
  {project.nodes.filter(n=>n.parentId).map(n=>{const a=positions.get(n.parentId!)!,b=positions.get(n.id)!;return <path key={`p-${n.id}`} className="edge" d={`M${a.x+170},${a.y+28} C${a.x+220},${a.y+28} ${b.x-50},${b.y+28} ${b.x},${b.y+28}`}/>})}
  {project.relations.map(r=>{const a=positions.get(r.sourceId),b=positions.get(r.targetId),s=getSchema(project,r.typeId);if(!a||!b)return null;return <g key={r.id} onClick={()=>onSelect({kind:'relation',id:r.id})} className="relation-line"><path className={`edge relation ${s?.relationStyle||''}`} d={`M${a.x+85},${a.y+58} Q${(a.x+b.x)/2},${Math.min(a.y,b.y)-35} ${b.x+85},${b.y+58}`}/><text x={(a.x+b.x)/2+85} y={(a.y+b.y)/2-10}>{s?.name}</text></g>})}
  {project.nodes.map(n=>{const p=positions.get(n.id)!;const s=getSchema(project,n.typeId);return <g key={n.id} transform={`translate(${p.x} ${p.y})`} className={`svg-node ${selection?.kind==='node'&&selection.id===n.id?'selected':''}`} onClick={()=>onSelect({kind:'node',id:n.id})}><rect width="170" height="58"/><rect className="type-band" width="6" height="58" fill={s?.color}/><text x="18" y="25">{nodeLabel(project,n).slice(0,22)}</text><text className="type-text" x="18" y="43">{s?.name}</text></g>})}
 </svg></div></section>}
